/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cotizacion;

import admin.menuAdmin;
import java.util.Arrays;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
public class cotizar extends javax.swing.JFrame {

private String[] AreaMetropolitana={"Chimaltenango", "Guatemala", "Sacatepequez","Solola"};
private String[] AreaNorte={"Alta Verapaz", "Baja Verapaz", "Peten"};
private String[] AreaNOR={"Chiquimula","El progreso","Izabal","Jalapa","Zacapa"};  
private String[] AreaNOC={"Huehuetanango","Quiche","San Marcos","Totonicapan"};
private String[] AreaSURO={"Escuintla","Jutiapa","Santa Rosa"};
private String[] AreaSUC={"Quetzaltenango","Retalhuleu","Suchitepequez"};
private static int precioDfltAreaMetro=35;
private static int precioSpclAreaMetro=25;

private static double precioDfltNorte=68.50;
private static double precioSpclNorte=45.55;

private static double precioDfltAreaNOR=58.68;
private static double precioSpclAreaNOR=35.48;

private static double precioDfltAreaNOC=44.50;
private static double precioSpclAreaNOC=40;

private static double precioDfltSuro=38.68;
private static double precioSpclSuro=32.48;

private static double precioDfltSUC=34;
private static double precioSpclSUC=29;

    public static int getPrecioDfltAreaMetro() {
        return precioDfltAreaMetro;
    }

    public static int getPrecioSpclAreaMetro() {
        return precioSpclAreaMetro;
    }

    public static double getPrecioDfltNorte() {
        return precioDfltNorte;
    }

    public static double getPrecioSpclNorte() {
        return precioSpclNorte;
    }

    public static double getPrecioDfltAreaNOR() {
        return precioDfltAreaNOR;
    }

    public static double getPrecioSpclAreaNOR() {
        return precioSpclAreaNOR;
    }

    public static double getPrecioDfltAreaNOC() {
        return precioDfltAreaNOC;
    }

    public static double getPrecioSpclAreaNOC() {
        return precioSpclAreaNOC;
    }

    public static double getPrecioDfltSuro() {
        return precioDfltSuro;
    }

    public static double getPrecioSpclSuro() {
        return precioSpclSuro;
    }

    public static double getPrecioDfltSUC() {
        return precioDfltSUC;
    }

    public static double getPrecioSpclSUC() {
        return precioSpclSUC;
    }

    public cotizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Departamentos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PrecioEstandar = new javax.swing.JLabel();
        PrecioEspecial = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANEJO DE PRECIOS POR REGION");

        jLabel2.setText("Precios por Region");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metropolitana", "Noroccidente", "Nororiente", "Norte","Suroccidente","Suroriente" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Region");

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel4.setText("Departamentos abarcados");

        jButton2.setText("Regresar al menu");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Departamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PrecioEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrecioEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Departamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(PrecioEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(PrecioEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ElegirRegion();
        precios();   
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        dispose();
        menuAdmin menu = new menuAdmin();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    public String getjComboBox1() {
        return (String)jComboBox1.getSelectedItem();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cotizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cotizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cotizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cotizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cotizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Departamentos;
    private javax.swing.JLabel PrecioEspecial;
    private javax.swing.JLabel PrecioEstandar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
public void precios(){
    String regionSelecta = getjComboBox1();
        
        switch(regionSelecta) {
    case "Metropolitana":
        // código a ejecutar si la región es Metropolitana
        PrecioEstandar.setText("Precio estandar(entrega de 3-5 dias hablies): Q"+getPrecioDfltAreaMetro());
        PrecioEspecial.setText("Precio especial (entrega de 1-2 dias hablies): Q"+getPrecioSpclAreaMetro());
        break;
    case "Norte":
        // código a ejecutar si la región es Norte
        PrecioEstandar.setText("Precio estandar(entrega de 3-5 dias hablies): Q"+getPrecioDfltNorte());
        PrecioEspecial.setText("Precio especial (entrega de 1-2 dias hablies): Q"+getPrecioSpclNorte());
        break;
    case "Nororiente":
        // código a ejecutar si la región es Nororiente
        PrecioEstandar.setText("Precio estandar(entrega de 3-5 dias hablies): Q"+getPrecioDfltAreaNOR());
        PrecioEspecial.setText("Precio especial (entrega de 1-2 dias hablies): Q"+getPrecioSpclAreaNOR());
        break;
    case "Noroccidente":
        // código a ejecutar si la región es Noroccidente
        PrecioEstandar.setText("Precio estandar(entrega de 3-5 dias hablies): Q"+getPrecioDfltAreaNOC());
        PrecioEspecial.setText("Precio especial (entrega de 1-2 dias hablies): Q"+getPrecioSpclAreaNOC());
        break;
    case "Suroccidente":
        // código a ejecutar si la región es Suroccidente
        PrecioEstandar.setText("Precio estandar(entrega de 3-5 dias hablies): Q"+getPrecioDfltSuro());
        PrecioEspecial.setText("Precio especial (entrega de 1-2 dias hablies): Q"+getPrecioSpclSuro());
        break;
    case "Suroriente":
        // código a ejecutar si la región es Suroriente
        PrecioEstandar.setText("Precio estandar(entrega de 3-5 dias hablies): Q"+getPrecioDfltSUC());
        PrecioEspecial.setText("Precio especial (entrega de 1-2 dias hablies): Q"+getPrecioSpclSUC());
        break;
    default:
        // código a ejecutar si la región no coincide con ninguna de las anteriores
        JOptionPane.showMessageDialog(null, "Ingrese una Region", "Error", JOptionPane.ERROR_MESSAGE);
        break;
}
}
public void ElegirRegion(){
String regionSelecta = getjComboBox1();
        
        switch(regionSelecta) {
    case "Metropolitana":
        // código a ejecutar si la región es Metropolitana
        String metro = Arrays.toString(AreaMetropolitana);
        Departamentos.setText(metro);
        break;
    case "Norte":
        // código a ejecutar si la región es Norte
        String Norte = Arrays.toString(AreaNorte);
        Departamentos.setText(Norte);
        break;
    case "Nororiente":
        // código a ejecutar si la región es Nororiente
        String NOR = Arrays.toString(AreaNOR);
        Departamentos.setText(NOR);
        break;
    case "Noroccidente":
        // código a ejecutar si la región es Noroccidente
        String NOC = Arrays.toString(AreaNOC);
        Departamentos.setText(NOC);
        break;
    case "Suroccidente":
        // código a ejecutar si la región es Suroccidente
        String SURO = Arrays.toString(AreaSURO);
        Departamentos.setText(SURO);
        break;
    case "Suroriente":
        // código a ejecutar si la región es Suroriente
        String SUC = Arrays.toString(AreaSUC);
        Departamentos.setText(SUC);
        break;
    default:
        // código a ejecutar si la región no coincide con ninguna de las anteriores
        JOptionPane.showMessageDialog(null, "Ingrese una Region", "Error", JOptionPane.ERROR_MESSAGE);
        break;
}
}
}
