/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clientes.DatosFacturables;

import static admin.manejoUsr.indice;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import login.datausers;
import login.iu;

/**
 *
 * @author ricar
 */
public class IntefarDatosFacturacion extends javax.swing.JFrame {


    /**
     * Creates new form IntefarDatosFacturacion
     */
    public IntefarDatosFacturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NIT = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        RTU = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        RegistrarDatos = new javax.swing.JButton();
        EditarDatos = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos de facturacion");

        jLabel3.setText("Nombre Completo");

        jLabel4.setText("Direccion");

        NIT.setText("NIT");

        Buscar.setText("Buscar datos");
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarMouseClicked(evt);
            }
        });
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        RegistrarDatos.setText("Registrar datos");
        RegistrarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarDatosMouseClicked(evt);
            }
        });

        EditarDatos.setText("Editar datos");
        EditarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarDatosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(RegistrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(EditarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NIT, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RTU, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))))))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RTU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(RegistrarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(108, 108, 108))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseClicked
        // TODO add your handling code here:
datausers dta = new datausers();

if (DatosDeFacturacion.getDireccion().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Debe registrar sus datos primero");
} else {
    int index = indice(iu.getCorreoActual()) - 1;
    if (index >= 0 && index < DatosDeFacturacion.getDireccion().size()) {
        Name.setText(dta.getNm().get(indice(iu.getCorreoActual())) + " " + dta.getLstNm().get(indice(iu.getCorreoActual())));
        Direccion.setText(DatosDeFacturacion.getDireccion().get(index));
        RTU.setText(DatosDeFacturacion.getNIT().get(index));
    } else {
        JOptionPane.showMessageDialog(null, "No se encontraron datos de facturación para este usuario");
    }
}

            
        
        
    }//GEN-LAST:event_BuscarMouseClicked

    private void RegistrarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarDatosMouseClicked
        // TODO add your handling code here:
        int index = indice(iu.getCorreoActual());
    Clientes.DatosFacturables.DatosDeFacturacion datosFacturables = new Clientes.DatosFacturables.DatosDeFacturacion();
ArrayList<String> direccion = datosFacturables.getDireccion();
ArrayList<String> nit = datosFacturables.getNIT();

if (index >= 0) {
    JOptionPane.showMessageDialog(null, "Ya existe una dirección y NIT asociados a este usuario");
} else {
    String newDirec = JOptionPane.showInputDialog("Ingrese su nueva dirección");
    String newNIT = JOptionPane.showInputDialog("Ingrese el nuevo NIT");

    if (newDirec != null && newNIT != null && !newDirec.isEmpty() && !newNIT.isEmpty()) {
        direccion.add(newDirec);
        nit.add(newNIT);
        JOptionPane.showMessageDialog(null, "Datos registrados correctamente");
    } else {
        JOptionPane.showMessageDialog(null, "Debe ingresar una dirección y un NIT válidos");
    }
}
        
    }//GEN-LAST:event_RegistrarDatosMouseClicked

    private void EditarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarDatosMouseClicked
        // TODO add your handling code here:
       datausers dta = new datausers();

// Check if user has registered their data
if(DatosDeFacturacion.getDireccion().get(indice(iu.getCorreoActual())-1).isEmpty()){
    JOptionPane.showMessageDialog(null,"Debe registrar sus datos primero");
} else {
    int index = indice(iu.getCorreoActual());

    // Ask for confirmation before updating data
    int cambiardatos = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea cambiar los datos?", "Confirmar acción", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE); 

    if (cambiardatos == JOptionPane.YES_OPTION) {
        Object[] opciones = {"Nombre", "Direccion", "NIT"};
        int selectedOption = JOptionPane.showOptionDialog(null, "Seleccione una opción:", "Seleccionar dato", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opciones, opciones[0]);

        switch(selectedOption){
            case 0:
                String newName= JOptionPane.showInputDialog("Ingrese el nuevo nombre");
                String newLastName= JOptionPane.showInputDialog("Ingrese el nuevo apellido");
                // Update name and last name using the datausers object
                dta.getNm().set(index-1, newName);
                dta.getLstNm().set(index-1, newLastName);
                JOptionPane.showMessageDialog(null,"Nombre actualizado correctamente");
                break;
            case 1:
                String newDirec= JOptionPane.showInputDialog("Ingrese su nueva dirección");
                // Update direccion using the DatosDeFacturacion object
                DatosDeFacturacion.getDireccion().set(index-1, newDirec);
                JOptionPane.showMessageDialog(null,"Dirección actualizada correctamente");
                break;
            case 2:
                String newDPI= JOptionPane.showInputDialog("Ingrese el nuevo NIT");
                // Update NIT using the DatosDeFacturacion object
                DatosDeFacturacion.getNIT().set(index-1, newDPI);
                JOptionPane.showMessageDialog(null,"NIT actualizado correctamente");
                break;
            default:
                JOptionPane.showMessageDialog(null,"Opción inválida");
                break;
        }
    } else {
        JOptionPane.showMessageDialog(null,"Operación cancelada");
    }
}
         
    }//GEN-LAST:event_EditarDatosMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntefarDatosFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntefarDatosFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntefarDatosFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntefarDatosFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new IntefarDatosFacturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Direccion;
    private javax.swing.JButton EditarDatos;
    private javax.swing.JLabel NIT;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel RTU;
    private javax.swing.JButton RegistrarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
public int indice(String email){
         datausers dta = new datausers();
         int in;
         if(dta.getCorreos().contains(email)){
        in=dta.getCorreos().indexOf(email);
        return in;
    }
        return -1;
}   
    

}
